---

- name: install vault
  hosts: all
  become: true
  roles:
    - dco.vault.install
    - dco.vault.agent

- name: install consul
  hosts: all
  become: true
  roles:
    - dco.consul.base
    - dco.consul.client
    - dco.consul.agent

- name: install nomad
  hosts: all
  become: true
  roles:
    - dco.nomad.base
    - dco.nomad.agent
    - dco.nomad.server
    - dco.nomad.init
    - dco.nomad.client

- name: create the trigger file
  hosts: all
  become: true
  tasks:
  - name: Create opt/common directory
    file:
      path: "/opt/common"
      state: directory
      mode: "0755"
  - name: Create trigger file
    file:
      path: "{{ trigger_file_location }}"
      state: touch
