---

- name: install consul
  hosts: all
  become: true
  roles:
    - dco.consul.base
    - dco.consul.client


- name: install nomad
  hosts: all
  become: true
  vars:
    vault_address: "https://vault.devcastops.com:8200"
  roles:
    - dco.nomad.base
    - dco.nomad.client
