---

- name: install consul
  hosts: all
  become: true
  roles:
    - dco.consul.base
    - dco.consul.client
    - dco.consul.vault_tls

- name: install vault
  hosts: all
  become: true
  roles:
    - dco.vault.install


- name: install nomad
  hosts: all
  become: true
  vars:
    vault_address: "https://10.2.0.6:8200"
  roles:
    - dco.nomad.base
    - dco.nomad.client


- name: post nomad
  hosts: all
  become: true
  roles:
    - dco.nomad.postGolden
