---

- name: install consul
  hosts: all
  become: true
  roles:
    - dco.consul.base
    - dco.consul.client


- name: install nomad
  hosts: all
  become: true
  roles:
    - dco.nomad.base
    - dco.nomad.client
