---


- name: Consul_base
  hosts: all
  become: true
  roles:
    - role: dco.consul.base
    - role: dco.vault.install
    - role: dco.vault.agent

- name: Vault
  hosts: all
  become: true
  roles:
    - role: dco.vault.server
    - role: dco.vault.init
    - role: dco.vault.ca_management

- name: Consul Server
  hosts: consul_server
  become: true
  vars:
    type: server
  roles:
    - role: dco.consul.agent
    - role: dco.consul.server