name: build

on:
  push:
    branches:
      - "main"

env:
  PACKER_PRODUCT_VERSION: "latest" 

jobs:
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    outputs:
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
      # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

  build-image:
    needs: changed_files
    name: Build Packer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ "control-plane", "nomad-server" ]
      fail-fast: false
    steps:

      - name: Checkout Repository
        if: contains(needs.changed_files.outputs.all_changed_files, 'common')  || contains(needs.changed_files.outputs.all_changed_files, matrix.image)
        uses: actions/checkout@v3

      - id: 'auth'
        name: Authenticate to Google Cloud
        if: contains(needs.changed_files.outputs.all_changed_files, 'common')  || contains(needs.changed_files.outputs.all_changed_files, matrix.image)
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        if: contains(needs.changed_files.outputs.all_changed_files, 'common')  || contains(needs.changed_files.outputs.all_changed_files, matrix.image)
        id: setup
        with:
          version: ${{ env.PACKER_PRODUCT_VERSION }}

      - name: "Install Ansible"
        uses: alex-oleshkevich/setup-ansible@v1.0.1
        if: contains(needs.changed_files.outputs.all_changed_files, 'common')  || contains(needs.changed_files.outputs.all_changed_files, matrix.image)
        with:
          version: "9.5.1"

      - name: Run `packer init`
        if: contains(needs.changed_files.outputs.all_changed_files, 'common')  || contains(needs.changed_files.outputs.all_changed_files, matrix.image)
        id: init
        run: packer init .

      - name: Run `packer validate`
        if: contains(needs.changed_files.outputs.all_changed_files, 'common')  || contains(needs.changed_files.outputs.all_changed_files, matrix.image)
        id: validate
        run: |
          ansible-playbook --version
          packer validate .

      - name: Packer Build
        if: contains(needs.changed_files.outputs.all_changed_files, 'common')  || contains(needs.changed_files.outputs.all_changed_files, matrix.image)
        env:
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
        run: |
          sed -e '$s/$/\n/' -s ${{ matrix.image }}.pkr.hcl common_*.hcl > image.pkr.hcl
          packer build -color=false -on-error=cleanup -debug image.pkr.hcl
