name: DCO GCP Images

on:
  push:
    branches:
      - "main"
  workflow_dispatch:


env:
  PACKER_PRODUCT_VERSION: "latest" 

jobs:
  build-image:
    strategy:
      matrix:
        image: [ "control-plane", "nomad-server" ]
    runs-on: ubuntu-latest
    name: Build Packer
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PACKER_PRODUCT_VERSION }}

      - name: "Install Ansible"
        uses: alex-oleshkevich/setup-ansible@v1.0.1
        with:
          version: "9.5.1"

      - name: Run `packer init`
        id: init
        run: packer init .

      - name: Run `packer validate`
        id: validate
        run: |
          ansible-playbook --version
          packer validate .

      - name: Packer Build
        env:
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
        run: |
          packer build -color=false -on-error=cleanup -debug $( echo common_*.pkr.hcl ) ${{ matrix.image }}.pkr.hcl
